@startuml
(*) --> [Observation] "Raw Data, up to 10 kHz"

if "data stream (R1 level)" then
        
        -->  "Data Volume Reduction (DVR)"

        -->  "Disk"

        '--> "Fitting of muons"

        '-right-> (*)
else
        ->[Muon tagging (R1)] "Muon candidates 10 - 20 Hz"
       
        -->  "Without DVR"

        -->  "Disk"

        

endif


@enduml



