data:
  evfile : '/Volumes/Crucial/astrodata/fermi_lat/rcw86_alltime/PH.txt'
  scfile : '/Volumes/Crucial/astrodata/fermi_lat/rcw86_alltime/L25021711174938FCB76E09_SC00.fits'

binning:
  roiwidth   : 7.5
  binsz      : 0.02
  binsperdec : 8
  coordsys   : 'CEL'

selection :
  emin : 1000
  emax : 500000
  tmin: 473299204 # Start time in MET seconds, 1 January 2016
  tmax: 760060804  # End time in MET seconds
  zmax    : 90
  evclass : 128
  evtype  : 3
  ra: 220.76
  dec : -62.45

gtlike:
  edisp : True
  irfs : 'P8R3_SOURCE_V3'
  edisp_disable : ['isodiff','galdiff']

model:
  src_roiwidth : 7.5
  galdiff  : '/Users/vdk/miniforge3/pkgs/fermitools-data-0.18-0/share/fermitools/refdata/fermi/galdiffuse/gll_iem_v07.fits'
  isodiff  : '/Users/vdk/miniforge3/pkgs/fermitools-data-0.18-0/share/fermitools/refdata/fermi/galdiffuse/iso_P8R2_SOURCE_V6_v06.txt'
  catalogs: '/Users/vdk/shared/fermibottle/gll_psc_v35.fit'

fileio:
  usescratch: False
  outdir : '/Users/vdk/software/my_codebase/python/data_analysis/fermi_lat/rcw86/output_rcw_2016_2025'